# Generated by Django 4.2 on 2025-02-09 09:43

import conferenceApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, validators=[conferenceApp.models.validate_title]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=1000, message='Capacity cannot exceed 1000'), django.core.validators.MinValueValidator(limit_value=0, message='Capacity must be positive')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Price must be positive')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='program',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'])]),
        ),
    ]
